name: JPacman CI with Gradle
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # Update Gradle Wrapper version
    - name: Update Gradle Wrapper
      run: |
        wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
        unzip -d /opt gradle-7.6-bin.zip
        ln -s /opt/gradle-7.6/bin/gradle /usr/local/bin/gradle
        rm gradle-7.6-bin.zip
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Update Gradle Wrapper Version
      run: |
        ./gradlew wrapper --gradle-version 7.6 --distribution-type bin
        ./gradlew --version

    - name: Build with Gradle
      run: |
        export DISPLAY=:99
        sudo Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        ./gradlew clean build --no-daemon --info

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v3
